GITHUB_TOKEN_URL = "https://github.com/login/oauth/access_token"
GITHUB_API = "https://api.github.com"
ORG_LOGIN = "HubESI"
ESIHUB_LINK = f"https://github.com/{ORG_LOGIN}"
INV_TEAM = "base-team"
JOIN_ESI_HUB_GP_LINK = "https://hubesi.github.io/join"
